### ISSUE TITLE
How to authenticate?

### ISSUE THREAD

**Issue by galipmedia** [crrobinson14/vue-rethinkdb#1]
I am running through this code trying to understand how we initially authenticate a user in the database, via login or signup for example. Also how to have some queries public and some require authentication, it seems everything is guarded by auth at the moment.

**Comment by crrobinson14** [comment]
@galipmedia This service is meant to be used to "bridge" between VueJS and a back-end database. I provided some sample authentication code but it's just meant to be used as a guide. You have three options here:

1. Use the code I provided. This is activated by the following steps:
    1. Set the `JWT_SECRET` environment variable (or modify [this line](https://github.com/crrobinson14/vue-rethinkdb/blob/master/bridge/lib/Socket.js#L6) when starting the bridge service,
    1. Configure your client to emit `'auth', params { authToken: 'JWTTOKEN' }` immediately after sending the SocketCluster `#handshake` message on connect.
    1. Configure your queries to examine `socket.session` for the decoded token values to use in your business logic. [See this example](https://github.com/crrobinson14/vue-rethinkdb/blob/master/bridge/lib/Queries.js#L18-L23).
1. Use SocketCluster's built in authentication mechanism. I love SocketCluster but tbh never figured this part out because I was writing my own client libraries so I just bypassed it. But it does have a [well thought out auth mechanism](https://socketcluster.io/#!/docs/authentication) you may want to try, especially if you use their client-side libraries.
1. Add your own custom logic?

At the end of the day, bridging clients with back-end services almost always has unique requirements in every project. This project isn't necessarily meant to be a "use as-is" drop-in solution for all of them. It's meant to give people a running start, basically "well, here's ONE way to do it..."

If there's anything you don't like, you're meant to customize from there. Don't like SocketCluster? There's no reason at all you couldn't change the bridge to use Socket.IO or similar. Want OpenID Connect or OAuth authentication? Well, the "bridge" is just a NodeJS server, and SocketCluster is built on top of Express. There's no reason you couldn't drop [PassportJS](http://www.passportjs.org/) in there instead.

In fact, dirty little secret: there's no reason you have to use RethinkDB as a back-end either! That's what I wanted to talk to in my app, and it seemed to be a hole to fill in the community. But the actual back-end is invisible to the client - you could easily change it to Cassandra or whatever else and the client would never know!

Hope this helps...
